FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/
COPY shared/package*.json ./shared/

RUN npm install

COPY . .

RUN npm run build -w shared
RUN npm run build -w client

WORKDIR /app/client

EXPOSE 3000

CMD ["npm", "run", "start"]