image: public.ecr.aws/docker/library/node:20

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "main"
  - if: $CI_COMMIT_BRANCH == "development"

stages:
  - typecheck
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - client/.next/cache/
  policy: pull-push

default:
  before_script:
    - npm ci --cache .npm --prefer-offline

typecheck:
  stage: typecheck
  script:
    - npm run typecheck

build:
  stage: build
  script:
    - npm run build
  needs: ["typecheck"]

deploy:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
    - vercel build --prod --token="$VERCEL_TOKEN"
    - vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
