image: public.ecr.aws/docker/library/node:20

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_COMMIT_BRANCH == "development"

stages:
    - checks
    - test
    - build
    - deploy

cache:
    key:
        files:
            - package-lock.json
    paths:
        - .npm/
        - client/.next/cache/
    policy: pull-push

default:
    before_script:
        - npm ci --cache .npm --prefer-offline

formatcheck:
    stage: checks
    script:
        - npm run format:check

typecheck:
    stage: checks
    script:
        - npm run typecheck

lintcheck:
    stage: checks
    script:
        - npm run lint -- --max-warnings=0

test:
    stage: test
    script:
        - npm run test
    needs: 
        - formatcheck
        - typecheck
        - lintcheck

build:
    stage: build
    script:
        - npm run build
    needs: ["test"]

deploy:
    stage: deploy
    script:
        - apt-get update && apt-get install -y curl
        - curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_MAIN"
    needs: ["build"]
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
