image: public.ecr.aws/docker/library/node:20

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "main"
  - if: $CI_COMMIT_BRANCH == "development"

stages:
  - install
  - typecheck
  - build
  - deploy

cache:
  paths:
    - node_modules/
  
install:
  stage: install
  script:
    - npm ci

typecheck:
  stage: typecheck
  script:
    - npm run typecheck
  needs: ["install"]

build:
  stage: build
  script:
    - npm run build
  needs: ["typecheck"]

deploy:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
    - vercel build --prod --token="$VERCEL_TOKEN"
    - vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
