FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/
COPY shared/package*.json ./shared/

RUN npm install


# Copy source code
COPY . .

RUN npm run build -w shared
RUN npm run build -w server

EXPOSE 4000

CMD ["npm", "run", "start", "-w", "server"]